// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUOEpg4zH6gaU8cadBrBJJ_k3w4BUkJyQ',
    appId: '1:755499039846:web:8363425c37c8f3e83f01a7',
    messagingSenderId: '755499039846',
    projectId: 'dentallanch',
    authDomain: 'dentallanch.firebaseapp.com',
    storageBucket: 'dentallanch.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe_NmfUhQ8divyojKa7LDASwhQI3N7nko',
    appId: '1:755499039846:android:db2bd04b0db3a20e3f01a7',
    messagingSenderId: '755499039846',
    projectId: 'dentallanch',
    storageBucket: 'dentallanch.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTyaiVKA2LJOamqN07fDi_4l-Wx95UQK4',
    appId: '1:755499039846:ios:d8ff640de110c09b3f01a7',
    messagingSenderId: '755499039846',
    projectId: 'dentallanch',
    storageBucket: 'dentallanch.firebasestorage.app',
    iosBundleId: 'com.example.dentalLanch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTyaiVKA2LJOamqN07fDi_4l-Wx95UQK4',
    appId: '1:755499039846:ios:d8ff640de110c09b3f01a7',
    messagingSenderId: '755499039846',
    projectId: 'dentallanch',
    storageBucket: 'dentallanch.firebasestorage.app',
    iosBundleId: 'com.example.dentalLanch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUOEpg4zH6gaU8cadBrBJJ_k3w4BUkJyQ',
    appId: '1:755499039846:web:130fad52f3687f823f01a7',
    messagingSenderId: '755499039846',
    projectId: 'dentallanch',
    authDomain: 'dentallanch.firebaseapp.com',
    storageBucket: 'dentallanch.firebasestorage.app',
  );
}
